import type { TableColumnMeta } from './mssql.service.js';

export type InstructionAction = 'insert' | 'unknown';

export interface ParsedInstruction {
  action: InstructionAction;
  table_name: string;
  description: string;
  columns: string[];
  rows: string[][];
  row_count: number;
  schema_columns?: TableColumnMeta[];
}

export interface ParseResult {
  parsed: ParsedInstruction;
  sql: string;
  warnings: string[];
}

function assertSafeIdentifier(name: string): string {
  const trimmed = name.trim();
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(trimmed)) {
    throw new Error(`Invalid identifier: "${name}"`);
  }
  return trimmed;
}

function parseInstructionLine(line: string): { action: InstructionAction; table_name: string } {
  const trimmed = line.trim();

  const addRecord = trimmed.match(/^add\s+record\s+([A-Za-z_][A-Za-z0-9_]*)/i);
  if (addRecord) {
    return { action: 'insert', table_name: assertSafeIdentifier(addRecord[1]) };
  }

  const insertInto = trimmed.match(/^insert\s+(?:into\s+)?([A-Za-z_][A-Za-z0-9_]*)/i);
  if (insertInto) {
    return { action: 'insert', table_name: assertSafeIdentifier(insertInto[1]) };
  }

  throw new Error(
    'Could not detect instruction. Start with a line like: Add record gen_usergroup'
  );
}

function splitDataLine(line: string): string[] {
  if (line.includes('\t')) {
    return line.split('\t').map((v) => v.trim());
  }
  return line.trim().split(/\s{2,}|\s+/).map((v) => v.trim()).filter(Boolean);
}

function defaultColumns(count: number): string[] {
  return Array.from({ length: count }, (_, i) => `col${i + 1}`);
}

function parseColumnsOverride(input?: string, count?: number): string[] | null {
  if (!input?.trim()) return null;

  const cols = input
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean);

  if (count && cols.length !== count) {
    throw new Error(`Expected ${count} column names, got ${cols.length}`);
  }

  for (const col of cols) {
    assertSafeIdentifier(col);
  }

  return cols;
}

/** Columns that can receive values in an INSERT (skip identity). */
export function getInsertableColumns(schema: TableColumnMeta[]): TableColumnMeta[] {
  return schema.filter((c) => !c.is_identity);
}

function mapColumnsFromSchema(
  schema: TableColumnMeta[],
  valueCount: number,
  rows: string[][]
): { columns: string[]; schemaSlice: TableColumnMeta[]; rows: string[][]; warnings: string[] } {
  const insertable = getInsertableColumns(schema);
  const warnings: string[] = [];

  if (valueCount === insertable.length) {
    return {
      columns: insertable.map((c) => c.column_name),
      schemaSlice: insertable,
      rows,
      warnings,
    };
  }

  // Pasted values include identity column(s) — drop those values per row
  if (valueCount === schema.length && schema.some((c) => c.is_identity)) {
    const alignedRows = rows.map((row) =>
      schema
        .map((col, i) => ({ col, val: row[i] }))
        .filter((x) => !x.col.is_identity)
        .map((x) => x.val)
    );
    warnings.push('Ignored identity column value(s) from pasted data (auto-generated by SQL Server).');
    return {
      columns: insertable.map((c) => c.column_name),
      schemaSlice: insertable,
      rows: alignedRows,
      warnings,
    };
  }

  if (insertable.length > valueCount) {
    const slice = insertable.slice(0, valueCount);
    warnings.push(
      `Table has ${insertable.length} insertable columns but pasted data has ${valueCount}. Using first ${valueCount} columns: ${slice.map((c) => c.column_name).join(', ')}`
    );
    return {
      columns: slice.map((c) => c.column_name),
      schemaSlice: slice,
      rows,
      warnings,
    };
  }

  throw new Error(
    `Pasted data has ${valueCount} values but table only has ${insertable.length} insertable columns (excluding identity).`
  );
}

function formatSqlValue(value: string, col?: TableColumnMeta): string {
  const trimmed = value.trim();

  if (/^null$/i.test(trimmed)) {
    return 'NULL';
  }

  const type = (col?.data_type ?? '').toLowerCase();
  const isStringType = ['char', 'nchar', 'varchar', 'nvarchar', 'text', 'ntext'].includes(type);

  if (type === 'bit' || (!isStringType && /^(true|false)$/i.test(trimmed))) {
    return /^true$/i.test(trimmed) ? '1' : /^false$/i.test(trimmed) ? '0' : trimmed;
  }

  if (
    !isStringType &&
    (['int', 'bigint', 'smallint', 'tinyint', 'decimal', 'numeric', 'float', 'real', 'money', 'smallmoney'].includes(type) ||
      /^-?\d+(\.\d+)?$/.test(trimmed))
  ) {
    return trimmed;
  }

  const escaped = trimmed.replace(/'/g, "''");
  return `'${escaped}'`;
}

function rowExistsCondition(
  columns: string[],
  row: string[],
  schemaColumns?: TableColumnMeta[]
): string {
  return columns
    .map((col, i) => {
      const colMeta = schemaColumns?.[i];
      const colName = assertSafeIdentifier(col);
      const val = formatSqlValue(row[i], colMeta);
      const type = (colMeta?.data_type ?? '').toLowerCase();
      if (type === 'nchar' || type === 'char') {
        return `RTRIM([${colName}]) = RTRIM(${val})`;
      }
      return `[${colName}] = ${val}`;
    })
    .join(' AND ');
}

export function generateInsertSql(
  tableName: string,
  columns: string[],
  rows: string[][],
  schemaColumns?: TableColumnMeta[]
): string {
  const table = assertSafeIdentifier(tableName);
  const quotedCols = columns.map((c) => `[${assertSafeIdentifier(c)}]`).join(', ');

  const rowStatements = rows.map((row) => {
    const vals = row.map((val, i) => formatSqlValue(val, schemaColumns?.[i]));
    const where = rowExistsCondition(columns, row, schemaColumns);
    return `IF NOT EXISTS (SELECT 1 FROM dbo.${table} WHERE ${where})
BEGIN
    INSERT INTO dbo.${table} (${quotedCols})
    VALUES (${vals.join(', ')});
END`;
  });

  return `-- ${table}: insert ${rows.length} row(s) (safe to re-run)\n${rowStatements.join('\n\n')}`;
}

export function parseBossInstructions(
  text: string,
  options: {
    table_name: string;
    column_names?: string;
    schema_columns?: TableColumnMeta[];
  }
): ParseResult {
  const warnings: string[] = [];
  const table_name = assertSafeIdentifier(options.table_name);

  const lines = text
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0);

  if (lines.length === 0) {
    throw new Error('Paste data rows first');
  }

  // Support legacy format: "Add record tablename" on first line
  let dataLines = lines;
  const firstLineInstruction = lines[0].match(/^(?:add\s+record|insert\s+(?:into\s+)?)\s*([A-Za-z_][A-Za-z0-9_]*)/i);
  if (firstLineInstruction) {
    dataLines = lines.slice(1);
    if (dataLines.length === 0) {
      throw new Error('No data rows found below the instruction line');
    }
  }

  const rows = dataLines.map(splitDataLine);
  const valueCount = rows[0].length;

  if (valueCount === 0) {
    throw new Error('Could not read values from the first data row');
  }

  for (let i = 1; i < rows.length; i++) {
    if (rows[i].length !== valueCount) {
      throw new Error(
        `Row ${i + 1} has ${rows[i].length} values, but row 1 has ${valueCount}`
      );
    }
  }

  let columns: string[];
  let schemaSlice: TableColumnMeta[] | undefined;
  let alignedRows = rows;

  if (options.schema_columns?.length) {
    const mapped = mapColumnsFromSchema(options.schema_columns, valueCount, rows);
    columns = mapped.columns;
    schemaSlice = mapped.schemaSlice;
    alignedRows = mapped.rows;
    warnings.push(...mapped.warnings);
    warnings.push(`Column names loaded from POS table schema (${table_name})`);
  } else {
    columns = parseColumnsOverride(options.column_names, valueCount) ?? defaultColumns(valueCount);
    warnings.push(
      `Select a table from POS to load real column names. Using ${columns.join(', ')} for now.`
    );
  }

  const sql = generateInsertSql(table_name, columns, alignedRows, schemaSlice);
  const description = `Add ${rows.length} record(s) to ${table_name}`;

  return {
    parsed: {
      action: 'insert',
      table_name,
      description,
      columns,
      rows: alignedRows,
      row_count: rows.length,
      schema_columns: schemaSlice ?? options.schema_columns,
    },
    sql,
    warnings,
  };
}
